/* UU的小馆 · 现在不需要编辑代码：登录“管理员”后，网站文字、每周问题、我的画都可以直接在网页里改。 */

const ADMIN_PASSWORD = "UU2026";
const weeklyQuestionDefault = {
  zh: "如果今天是一种颜色，你会选择什么颜色？",
  en: "If today were a color, what color would it be?",
  placeholderZh: "比如：今天是很淡很淡的薄荷绿……",
  placeholderEn: "Maybe: a very soft mint green…"
};

const baseArtworks = [
  {type:"series",category:"colored",date:"2026-09-21",title:"示例：我的第一组画",note:"把属于同一个故事的几幅画放在这里。",images:[
    {image:"images/series-01.jpg",title:"第一张"},{image:"images/series-02.jpg",title:"第二张"},{image:"images/series-03.jpg",title:"第三张"}
  ]},
  {type:"single",category:"sketch",date:"2026-09-20",title:"随手画的小鸟",image:"images/sketch-01.jpg",note:"一个很普通的下午，突然想画一只鸟。"}
];

const translations = {
  zh:{
    navSubmit:"投稿",navColored:"有色画",navSketches:"随笔",navTogether:"一起玩",navUuTalk:"UU·和大家说的话",navAbout:"关于",navAdmin:"管理员",navDirectory:"目录",directoryTitle:"目录",directoryDesc:"想去哪里，就点哪里吧～",directorySubmit:"把你的画放进大家的小世界",directoryColored:"看看UU认真留下来的彩色作品",directorySketches:"一些随手画下来的小念头",directoryTogether:"问题、留言、大家的小世界",directoryUuTalk:"看看UU想留给大家的话",directoryAdmin:"管理员专属的小房间",adminTalk:"UU的话",
    heroEyebrow:"A LITTLE PLACE FOR MY DRAWINGS",heroTitle:"UU的小馆",heroIntro:"一页一页，收藏我画过的世界。<br>慢慢画，也慢慢长大。",enter:"进入小馆",
    coloredTitle:"有色画",coloredDesc:"彩色、完整的作品，以及那些被我认真留下来的画。",sketchTitle:"随笔",sketchDesc:"一些随手画下来的东西。小鸟、人物、风景、一个突然出现的念头。",
    submissionPageTitle:"投稿",submissionPageDesc:"如果你愿意，也可以把你的画放进UU的小馆。",shareTitle:"也让我看看你的世界吧。",shareDesc:"把你的画上传给UU，审核通过后会出现在大家的小世界。",previewSubmission:"打开投稿表单",choosePhoto:"放一张你的画",uploadPhoto:"点这里选择照片",uploadHint:"支持 JPG / PNG / WEBP",submissionName:"你的名字（可不填）",submissionNamePlaceholder:"匿名也可以",artName:"作品名字",artNamePlaceholder:"给你的画取个名字",sayAboutArt:"想说的话",artNotePlaceholder:"介绍一下这幅画……",submitArt:"投稿这幅画 ♡",submissionNote:"投稿会先进入UU的审核区。通过后才会公开。",
    togetherTitle:"一起玩",togetherDesc:"这里不只是我的画廊。也想留一点位置，给你的想法和你的世界。",questionTitle:weeklyQuestionDefault.zh,writeOne:"写下一句话",questionPlaceholder:weeklyQuestionDefault.placeholderZh,leaveAnswer:"留下答案 ♡",
    guestbookTitle:"你在想什么呢～写下来吧",nameOptional:"名字（可不填）",anonymous:"匿名也可以",leaveMessage:"留一句话",messagePlaceholder:"写下你想留下的话……",writeGuestbook:"写进留言簿 ♡",
    privateNoteTitle:"想和UU说一点悄悄话",privateNoteDesc:"这里的内容不会显示在大家的小世界里，只会送到UU的管理员区。",privateMessageLabel:"悄悄话",privateMessagePlaceholder:"想告诉UU什么呢……",sendPrivateMessage:"悄悄发给UU ♡",
    worldsTitle:"大家的小世界",worldsDesc:"投稿通过审核后，会直接出现在这里。",uuTalkTitle:"UU·和大家说的话",uuTalkDesc:"这里是UU想留给大家的一些话。每一篇都可以慢慢写。",uuTalkEmpty:"UU还没有写下新的话，等我慢慢来这里放下吧 ♡",communityEmpty:"还没有投稿，等你的第一幅画来这里住下吧 ♡",
    adminUploadShortcut:"上传我的画",adminTitle:"管理员小房间",adminDesc:"登录后，可以直接修改网站文字、每周问题、我的画，并审核投稿和查看私信。",adminLockedTitle:"UU的管理员入口",adminLockedDesc:"只有管理员登录后才能打开这个小房间。",adminPasswordPlaceholder:"管理员密码",adminUnlock:"登录管理员",adminPanelTitle:"UU的管理后台",adminLock:"退出",adminText:"网站文字",adminMyArt:"我的画",adminSubmissions:"投稿审核",adminMessages:"私信",adminSave:"保存修改",adminAddArt:"添加到我的画",adminDelete:"删除",adminApprove:"通过并展示",adminPending:"待审核",adminApproved:"已公开",adminPrivate:"私信 · 只有UU可见",blockedUsers:"已拉黑的用户",noBlockedUsers:"目前还没有拉黑用户。",blocked:"已拉黑",blockUser:"拉黑用户",unblockUser:"取消拉黑",replyToMessage:"回复",replyMessagePlaceholder:"写下要回复的话……",sendAdminReply:"发送回复",yourReply:"UU的回复",adminUuTalk:"UU的话",editUuTalk:"UU·和大家说的话",talkTitle:"标题",talkText:"内容",talkDate:"日期",talkTitlePlaceholder:"比如：给今天的一句话",talkTextPlaceholder:"写一点想和大家说的话……",publishTalk:"发布这句话 ♡",adminEmpty:"这里还没有内容。",adminNoMessages:"暂时没有悄悄话。",adminWrongPassword:"密码不对，再试一次吧 ♡",adminSaved:"已经保存啦 ♡",adminArtSaved:"这幅画已经放进你的画廊啦 ♡",adminNeedImage:"先选择一张图片哦 ♡",adminNeedTitle:"给作品写个名字吧 ♡",adminLoginHint:"当前版本是静态网站演示：管理员入口会在这台浏览器上保存内容。真正公开上线时，可以再接服务器登录，让管理员权限真正安全。",
    editHero:"首页",editGallery:"画廊",editTogether:"一起玩",editAbout:"关于",editWeekly:"每周问题",editZh:"中文",editEn:"English",editTitle:"标题",editText:"文字",editQuestion:"问题",editPlaceholder:"回答框提示语",editCategory:"分类",editDate:"日期",editImage:"作品图片",editName:"作品名",editNote:"作品说明",colored:"有色画",sketch:"随笔",single:"单幅",saved:"谢谢你，把这份颜色留在这里了 ♡",guestSaved:"已经写进这本小小留言簿了 ♡",empty:"先写一点点吧 ♡",unsafe:"这句话里有不太友善的词，可以换一种温柔的表达吗？",reply:"回复",replyPlaceholder:"写一条友善的回复……",sendReply:"回复 ♡",seriesWorks:"幅"
  },
  en:{
    navSubmit:"Submit",navColored:"Color Works",navSketches:"Sketches",navTogether:"Together",navUuTalk:"UU · Notes to Everyone",navAbout:"About",navAdmin:"Admin", navDirectory:"Directory", directoryTitle:"Directory", directoryDesc:"Choose where you want to go~", directorySubmit:"Share your art with everyone", directoryColored:"Browse UU's colored works", directorySketches:"Little sketches and passing thoughts", directoryTogether:"Questions, guestbook, and everyone's worlds", directoryUuTalk:"Notes UU wants to leave for everyone", directoryAdmin:"Private admin room", adminTalk:"UU's notes",
    heroEyebrow:"A LITTLE PLACE FOR MY DRAWINGS",heroTitle:"UU's Little Gallery",heroIntro:"A little place for all the worlds I draw.<br>Drawing slowly, growing slowly.",enter:"Enter the gallery",
    coloredTitle:"Color Works",coloredDesc:"Finished pieces, colorful worlds, and drawings I wanted to keep.",sketchTitle:"Sketches",sketchDesc:"Little things I draw along the way — birds, people, landscapes, passing thoughts.",
    submissionPageTitle:"Submit Your Art",submissionPageDesc:"If you would like, you can place a little piece of your art in UU's Little Gallery.",shareTitle:"Show me a little piece of your world.",shareDesc:"Upload your art to UU. After approval, it will appear in Everyone's Little Worlds.",previewSubmission:"Open submission form",choosePhoto:"Add a photo of your art",uploadPhoto:"Click here to choose a photo",uploadHint:"JPG / PNG / WEBP",submissionName:"Your name (optional)",submissionNamePlaceholder:"Anonymous is okay",artName:"Artwork title",artNamePlaceholder:"Give your artwork a name",sayAboutArt:"A little note",artNotePlaceholder:"Tell us about this drawing…",submitArt:"Submit this artwork ♡",submissionNote:"Submissions go to UU's private review area first. Only approved work becomes public.",
    togetherTitle:"Let's Make Something Together",togetherDesc:"This isn't only my gallery. There is a little room here for your thoughts and your world too.",questionTitle:weeklyQuestionDefault.en,writeOne:"Write a little",questionPlaceholder:weeklyQuestionDefault.placeholderEn,leaveAnswer:"Leave an answer ♡",
    guestbookTitle:"What are you thinking? Write it down~",nameOptional:"Name (optional)",anonymous:"Anonymous is okay",leaveMessage:"Leave a note",messagePlaceholder:"Write something you'd like to leave…",writeGuestbook:"Write in the guestbook ♡",
    privateNoteTitle:"A little private note for UU",privateNoteDesc:"This will not appear in Everyone's Little Worlds. It goes only to UU's admin area.",privateMessageLabel:"Private note",privateMessagePlaceholder:"What would you like to tell UU…",sendPrivateMessage:"Send quietly to UU ♡",
    worldsTitle:"Everyone's Little Worlds",worldsDesc:"Approved submissions appear here directly.",uuTalkTitle:"UU · Notes to Everyone",uuTalkDesc:"A little page for notes UU wants to leave for everyone.",uuTalkEmpty:"UU hasn't written a new note yet. Come back soon ♡",communityEmpty:"No submissions yet. Maybe your first drawing will live here ♡",
    adminUploadShortcut:"Upload my art",adminTitle:"Admin Corner",adminDesc:"After logging in, you can edit the website text, weekly question, your own art, submissions, and private notes.",adminLockedTitle:"UU's Admin Entrance",adminLockedDesc:"Only the administrator can open this little room.",adminPasswordPlaceholder:"Admin password",adminUnlock:"Log in as admin",adminPanelTitle:"UU's Admin Desk",adminLock:"Log out",adminText:"Website Text",adminMyArt:"My Art",adminSubmissions:"Submissions",adminMessages:"Private Notes",adminSave:"Save changes",adminAddArt:"Add to my gallery",adminDelete:"Delete",adminApprove:"Approve & show",adminPending:"Pending",adminApproved:"Public",adminPrivate:"Private · only UU can see",blockedUsers:"Blocked users",noBlockedUsers:"No blocked users yet.",blocked:"Blocked",blockUser:"Block user",unblockUser:"Unblock",replyToMessage:"Reply",replyMessagePlaceholder:"Write a reply…",sendAdminReply:"Send reply",yourReply:"UU's reply",adminUuTalk:"UU's Notes",editUuTalk:"UU · Notes to Everyone",talkTitle:"Title",talkText:"Message",talkDate:"Date",talkTitlePlaceholder:"For example: A little note for today",talkTextPlaceholder:"Write something you'd like to tell everyone…",publishTalk:"Publish this note ♡",adminEmpty:"Nothing here yet.",adminNoMessages:"No private notes yet.",adminWrongPassword:"That password is not right ♡",adminSaved:"Saved ♡",adminArtSaved:"This artwork is now in your gallery ♡",adminNeedImage:"Please choose an image first ♡",adminNeedTitle:"Give the artwork a title ♡",adminLoginHint:"This version is a static-site demo: the admin data is stored in this browser. For a real public site, connect a server login so admin permissions are truly private.",
    editHero:"Home",editGallery:"Gallery",editTogether:"Together",editAbout:"About",editWeekly:"Weekly Question",editZh:"Chinese",editEn:"English",editTitle:"Title",editText:"Text",editQuestion:"Question",editPlaceholder:"Answer placeholder",editCategory:"Category",editDate:"Date",editImage:"Artwork image",editName:"Artwork title",editNote:"Artwork note",colored:"Color Works",sketch:"Sketches",single:"Single",saved:"Thank you for leaving your color here ♡",guestSaved:"Your note has been added to this little guestbook ♡",empty:"Write a little something first ♡",unsafe:"That message contains words that may be unkind. Could you try a gentler expression?",reply:"Reply",replyPlaceholder:"Write a kind reply…",sendReply:"Reply ♡",seriesWorks:"works"
  }
};

const blockedTerms=["fuck","shit","bitch","asshole","idiot","stupid","操","妈的","傻逼","煞笔","垃圾","去死","草泥马","他妈的"];
let language="zh",adminUnlocked=false,selectedSubmissionImage=null,selectedMyArtImage=null;
const $=id=>document.getElementById(id);
const t=k=>translations[language][k]||k;
const getStored=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const saveStored=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
function containsBlockedLanguage(text){const n=(text||"").toLowerCase().replace(/\s+/g,"");return blockedTerms.some(x=>n.includes(x.toLowerCase()));}
function escapeHtml(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML;}

const defaultContent={
  heroTitle:{zh:"UU的小馆",en:"UU's Little Gallery"},heroIntro:{zh:"一页一页，收藏我画过的世界。<br>慢慢画，也慢慢长大。",en:"A little place for all the worlds I draw.<br>Drawing slowly, growing slowly."},
  coloredTitle:{zh:"有色画",en:"Color Works"},coloredDesc:{zh:"彩色、完整的作品，以及那些被我认真留下来的画。",en:"Finished pieces, colorful worlds, and drawings I wanted to keep."},
  sketchTitle:{zh:"随笔",en:"Sketches"},sketchDesc:{zh:"一些随手画下来的东西。小鸟、人物、风景、一个突然出现的念头。",en:"Little things I draw along the way — birds, people, landscapes, passing thoughts."},
  togetherTitle:{zh:"一起玩",en:"Let's Make Something Together"},togetherDesc:{zh:"这里不只是我的画廊。也想留一点位置，给你的想法和你的世界。",en:"This isn't only my gallery. There is a little room here for your thoughts and your world too."},
  guestbookTitle:{zh:"你在想什么呢～写下来吧",en:"What are you thinking? Write it down~"},
  privateNoteTitle:{zh:"想和UU说一点悄悄话",en:"A little private note for UU"},privateNoteDesc:{zh:"这里的内容不会显示在大家的小世界里，只会送到UU的管理员区。",en:"This will not appear in Everyone's Little Worlds. It goes only to UU's admin area."},
  worldsTitle:{zh:"大家的小世界",en:"Everyone's Little Worlds"},worldsDesc:{zh:"投稿通过审核后，会直接出现在这里。",en:"Approved submissions appear here directly."},uuTalkTitle:{zh:"UU·和大家说的话",en:"UU · Notes to Everyone"},uuTalkDesc:{zh:"这里是UU想留给大家的一些话。每一篇都可以慢慢写。",en:"A little page for notes UU wants to leave for everyone."},
  aboutTitle:{zh:"关于这个小地方",en:"About this little place"},aboutP1:{zh:"这里是UU的小馆。我把画画过的时间，一点一点放进这里。",en:"This is UU's Little Gallery — a place where I keep pieces of time spent drawing."},aboutP2:{zh:"有些画很认真，有些只是随手画下来的。它们都值得被留下。",en:"Some drawings are carefully made, and some are just little moments. They all deserve a place."}
};
function getContent(){return {...defaultContent,...getStored("uu_site_content",{})};}
function getWeekly(){return getStored("uu_weekly_question",weeklyQuestionDefault);}
function getMyArt(){return getStored("uu_my_art",[]);}
function allArtworks(){return [...baseArtworks,...getMyArt()];}

function applyContentToPage(){
  const c=getContent();
  document.querySelectorAll("[data-content-key]").forEach(el=>{const key=el.dataset.contentKey;if(c[key])el.innerHTML=c[key][language];});
  const q=getWeekly();
  $("question-title").innerHTML=language==="zh"?q.zh:q.en;
  $("question-answer").placeholder=language==="zh"?q.placeholderZh:q.placeholderEn;
}
function applyLanguage(){
  document.documentElement.lang=language==="zh"?"zh-CN":"en";document.body.classList.toggle("language-en",language==="en");
  document.title=language==="zh"?"UU的小馆":"UU's Little Gallery";
  document.querySelectorAll("[data-i18n]").forEach(el=>el.innerHTML=t(el.dataset.i18n));
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));
  $("language-toggle").textContent=language==="zh"?"EN":"中";
  applyContentToPage();renderAll();if(adminUnlocked)renderAdminAll();
}
function formatDate(s){return new Intl.DateTimeFormat(language==="zh"?"zh-CN":"en-US",{year:"numeric",month:"long",day:"numeric"}).format(new Date(s+"T12:00:00"));}
function groupByYear(items){const years={};[...items].sort((a,b)=>b.date.localeCompare(a.date)).forEach(x=>{const y=x.date.slice(0,4),m=x.date.slice(0,7);years[y]??={};years[y][m]??=[];years[y][m].push(x);});return years;}
function createSingle(x){return `<article class="art-card"><img class="art-image" src="${x.image}" alt="${escapeHtml(x.title)}" loading="lazy"><div class="art-info"><h3 class="art-title">${escapeHtml(x.title)}</h3><p class="art-date">${formatDate(x.date)}</p>${x.note?`<p class="art-note">${escapeHtml(x.note)}</p>`:""}</div></article>`;}
function createSeries(x){return `<article class="series-card"><div class="series-head"><div><h3 class="series-title">${escapeHtml(x.title)}</h3><p class="series-meta">${formatDate(x.date)} · ${x.images.length}${t("seriesWorks")}</p>${x.note?`<p class="series-note">${escapeHtml(x.note)}</p>`:""}</div></div><div class="series-grid">${x.images.map(i=>`<figure><img class="art-image" src="${i.image}" alt="${escapeHtml(i.title||x.title)}" loading="lazy"><figcaption>${escapeHtml(i.title||"")}</figcaption></figure>`).join("")}</div></article>`;}
function renderGallery(id,items){
  const box=$(id);
  const years=groupByYear(items);
  const html=Object.entries(years).map(([y,months])=>{
    const monthHtml=Object.entries(months).map(([m,list])=>{
      const cards=list.map(x=>x.type==="series"?createSeries(x):createSingle(x)).join("");
      const monthName=new Date(m+"-01T12:00:00").toLocaleDateString(language==="zh"?"zh-CN":"en-US",{month:"long"});
      return `<div class="month-block"><h4>${monthName}</h4><div class="art-grid">${cards}</div></div>`;
    }).join("");
    return `<div class="year-block"><h3 class="year-title">${y}</h3>${monthHtml}</div>`;
  }).join("");
  box.innerHTML=html||`<p class="admin-empty">${t("adminEmpty")}</p>`;
}
function renderCommunityGallery(){const list=getStored("uu_submissions",[]).filter(x=>x.status==="approved");$("community-gallery").innerHTML=list.map(x=>`<article class="community-card"><img src="${x.image}" alt="${escapeHtml(x.title)}" loading="lazy"><div class="community-info"><h4>${escapeHtml(x.title)}</h4><p class="community-by">${escapeHtml(x.name||"匿名投稿")}</p>${x.note?`<p>${escapeHtml(x.note)}</p>`:""}</div></article>`).join("");$("community-empty").classList.toggle("hidden",list.length>0);}
function renderAll(){renderGallery("colored-gallery",allArtworks().filter(x=>x.category==="colored"));renderGallery("sketch-gallery",allArtworks().filter(x=>x.category==="sketch"));renderCommunityGallery();}

// 投稿
$("share-preview-button").addEventListener("click",()=>{$("share-preview").classList.toggle("hidden");});
$("share-image").addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;selectedSubmissionImage=f;const u=URL.createObjectURL(f);$("share-image-preview").innerHTML=`<img src="${u}" alt="preview">`;$("share-image-preview").classList.remove("hidden");});
$("share-submit-button").addEventListener("click",()=>{const title=$("share-title").value.trim(),note=$("share-note").value.trim();if(!selectedSubmissionImage){$("share-message").textContent=t("adminNeedImage");return}if(!title){$("share-message").textContent=t("adminNeedTitle");return}if(containsBlockedLanguage(title+note)){$("share-message").textContent=t("unsafe");return}const r=new FileReader();r.onload=()=>{const a=getStored("uu_submissions",[]);a.unshift({id:uid(),name:$("share-name").value.trim()||"匿名投稿",title,note,image:r.result,createdAt:new Date().toISOString(),status:"pending"});saveStored("uu_submissions",a);$("share-message").textContent=language==="zh"?"收到啦 ♡ 已送进UU的审核小房间。":"Got it ♡ It is now waiting in UU's review room.";$("share-name").value=$("share-title").value=$("share-note").value="";$("share-image").value="";selectedSubmissionImage=null;$("share-image-preview").classList.add("hidden");if(adminUnlocked)renderAdminAll();};r.readAsDataURL(selectedSubmissionImage);});

// 留言簿
function getGuestbook(){return getStored("uu_guestbook",[])}
function saveGuestbook(v){saveStored("uu_guestbook",v)}
function renderGuestbook(){const box=$("guestbook-list"),items=getGuestbook();box.innerHTML=items.map(x=>`<div class="guest-note"><strong>${escapeHtml(x.name||"匿名")}：</strong>${escapeHtml(x.message)}<button class="reply-button" data-reply="${x.id}">${t("reply")}</button><div class="reply-list">${(x.replies||[]).map(r=>`<div class="reply-note"><strong>${escapeHtml(r.name)}：</strong>${escapeHtml(r.message)}</div>`).join("")}</div><form class="reply-form hidden" data-reply-form="${x.id}"><input maxlength="40" placeholder="${t("anonymous")}"><textarea maxlength="180" placeholder="${t("replyPlaceholder")}"></textarea><button type="submit">${t("sendReply")}</button></form></div>`).join("");}
$("guestbook-form").addEventListener("submit",e=>{e.preventDefault();const name=$("guest-name").value.trim()||"匿名",message=$("guest-message").value.trim();if(!message){$("guestbook-message").textContent=t("empty");return}if(containsBlockedLanguage(message)){$("guestbook-message").textContent=t("unsafe");return}const a=getGuestbook();a.unshift({id:uid(),name,message,replies:[]});saveGuestbook(a);renderGuestbook();$("guestbook-form").reset();$("guestbook-message").textContent=t("guestSaved");});
$("guestbook-list").addEventListener("click",e=>{const b=e.target.closest("[data-reply]");if(b)document.querySelector(`[data-reply-form="${b.dataset.reply}"]`)?.classList.toggle("hidden");});
$("guestbook-list").addEventListener("submit",e=>{if(!e.target.matches("[data-reply-form]"))return;e.preventDefault();const id=e.target.dataset.reply,ins=e.target.querySelectorAll("input,textarea"),message=ins[1].value.trim();if(!message)return;if(containsBlockedLanguage(message)){alert(t("unsafe"));return}const a=getGuestbook(),item=a.find(x=>x.id===id);item.replies??=[];item.replies.push({name:ins[0].value.trim()||"匿名",message});saveGuestbook(a);renderGuestbook();});

// 私信
$("private-message-form").addEventListener("submit",e=>{e.preventDefault();const name=$("private-name").value.trim()||"匿名",message=$("private-message").value.trim();if(!message){$("private-message-status").textContent=t("empty");return}if(containsBlockedLanguage(message)){$("private-message-status").textContent=t("unsafe");return}const blocked=getStored("uu_blocked_users",[]);if(blocked.includes(name)){$("private-message-status").textContent=language==="zh"?"暂时不能发送悄悄话。":"Private messages are unavailable for this sender.";return}const a=getStored("uu_private_messages",[]);a.unshift({id:uid(),name,message,createdAt:new Date().toISOString(),reply:""});saveStored("uu_private_messages",a);$("private-message-status").textContent=language==="zh"?"已经悄悄送给UU啦 ♡":"Your private note has been sent to UU ♡";$("private-message-form").reset();if(adminUnlocked)renderAdminMessages();});

// 管理员后台
function getUuTalks(){return getStored("uu_uu_talks",[]);}
function renderUuTalks(){const list=$("uu-talk-list"),empty=$("uu-talk-empty"),items=getUuTalks().sort((a,b)=>b.createdAt.localeCompare(a.createdAt));if(!list)return;list.innerHTML=items.map(x=>`<article class="uu-talk-card"><div class="uu-talk-date">${escapeHtml(formatDate(x.date||x.createdAt.slice(0,10)))}</div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.text).replace(/\n/g,"<br>")}</p></article>`).join("");empty.classList.toggle("hidden",items.length>0);}

function renderAdminAll(){renderAdminEditor();renderAdminMyArt();renderAdminSubmissions();renderAdminMessages();renderAdminTalks();renderUuTalks();}
function field(key,label,large=false){const c=getContent(),v=c[key]||{zh:"",en:""};return `<div class="editor-field"><label>${label}</label><div class="editor-lang"><textarea data-content-edit="${key}" data-lang="zh" class="${large?"large":""}">${escapeHtml(v.zh)}</textarea><textarea data-content-edit="${key}" data-lang="en" class="${large?"large":""}">${escapeHtml(v.en)}</textarea></div><div class="editor-lang-label"><span>中文</span><span>English</span></div></div>`;}
function renderAdminEditor(){const q=getWeekly();$("admin-editor-panel").innerHTML=`<div class="admin-editor-grid"><div class="editor-section"><h3>${t("editHero")}</h3>${field("heroTitle",t("editTitle"))}${field("heroIntro",t("editText"),true)}</div><div class="editor-section"><h3>${t("editGallery")}</h3>${field("coloredTitle",t("colored")+" · "+t("editTitle"))}${field("coloredDesc",t("editText"),true)}${field("sketchTitle",t("sketch")+" · "+t("editTitle"))}${field("sketchDesc",t("editText"),true)}</div><div class="editor-section"><h3>${t("editTogether")}</h3>${field("togetherTitle",t("editTitle"))}${field("togetherDesc",t("editText"),true)}${field("guestbookTitle",t("editTitle"))}${field("privateNoteTitle",t("editTitle"))}${field("privateNoteDesc",t("editText"),true)}${field("worldsTitle",t("editTitle"))}${field("worldsDesc",t("editText"),true)}${field("uuTalkTitle",t("editUuTalk"))}${field("uuTalkDesc",t("editText"),true)}</div><div class="editor-section weekly-editor"><h3>${t("editWeekly")}</h3><div class="editor-lang"><div><label>中文</label><textarea id="weekly-zh" class="large">${escapeHtml(q.zh)}</textarea><textarea id="weekly-ph-zh">${escapeHtml(q.placeholderZh)}</textarea></div><div><label>English</label><textarea id="weekly-en" class="large">${escapeHtml(q.en)}</textarea><textarea id="weekly-ph-en">${escapeHtml(q.placeholderEn)}</textarea></div></div></div></div><button class="admin-save-main" id="save-site-content">${t("adminSave")}</button><p id="admin-content-message" class="form-message"></p>`;$("save-site-content").addEventListener("click",()=>{const c=getContent();document.querySelectorAll("[data-content-edit]").forEach(el=>{c[el.dataset.contentEdit]??={zh:"",en:""};c[el.dataset.contentEdit][el.dataset.lang]=el.value;});saveStored("uu_site_content",c);saveStored("uu_weekly_question",{zh:$("weekly-zh").value,en:$("weekly-en").value,placeholderZh:$("weekly-ph-zh").value,placeholderEn:$("weekly-ph-en").value});applyContentToPage();applyLanguage();$("admin-content-message").textContent=t("adminSaved");});}

function renderAdminMyArt(){const items=getMyArt();$("admin-myart-panel").innerHTML=`<div class="my-art-form"><h3>${t("adminMyArt")}</h3><label>${t("editImage")}</label><label class="upload-box" for="my-art-image"><span class="upload-icon">＋</span><span>${t("uploadPhoto")}</span></label><input id="my-art-image" class="visually-hidden" type="file" accept="image/*"><div id="my-art-preview" class="upload-preview hidden"></div><label>${t("editName")}</label><input id="my-art-title"><label>${t("editCategory")}</label><select id="my-art-category"><option value="colored">${t("colored")}</option><option value="sketch">${t("sketch")}</option></select><label>${t("editDate")}</label><input id="my-art-date" type="date" value="${new Date().toISOString().slice(0,10)}"><label>${t("editNote")}</label><textarea id="my-art-note"></textarea><button id="add-my-art" class="admin-save-main">${t("adminAddArt")}</button><p id="my-art-message" class="form-message"></p></div><div class="admin-own-list">${items.map(x=>`<article class="admin-own-item"><img src="${x.image}" alt="${escapeHtml(x.title)}"><div><h4>${escapeHtml(x.title)}</h4><p>${x.category==="colored"?t("colored"):t("sketch")} · ${escapeHtml(x.date)}</p>${x.note?`<p>${escapeHtml(x.note)}</p>`:""}<button class="danger-button" data-own-delete="${x.id}">${t("adminDelete")}</button></div></article>`).join("")||`<p class="admin-empty">${t("adminEmpty")}</p>`}</div>`;$("my-art-image").addEventListener("change",e=>{selectedMyArtImage=e.target.files?.[0]||null;if(selectedMyArtImage){const u=URL.createObjectURL(selectedMyArtImage);$("my-art-preview").innerHTML=`<img src="${u}" alt="preview">`;$("my-art-preview").classList.remove("hidden");}});$("add-my-art").addEventListener("click",()=>{const title=$("my-art-title").value.trim(),f=selectedMyArtImage;if(!f){$("my-art-message").textContent=t("adminNeedImage");return}if(!title){$("my-art-message").textContent=t("adminNeedTitle");return}const r=new FileReader();r.onload=()=>{const a=getMyArt();a.unshift({type:"single",category:$("my-art-category").value,date:$("my-art-date").value,title,note:$("my-art-note").value.trim(),image:r.result,id:uid()});saveStored("uu_my_art",a);selectedMyArtImage=null;renderAdminMyArt();renderAll();};r.readAsDataURL(f);});$("admin-myart-panel").addEventListener("click",e=>{const b=e.target.closest("[data-own-delete]");if(!b)return;saveStored("uu_my_art",getMyArt().filter(x=>x.id!==b.dataset.ownDelete));renderAdminMyArt();renderAll();});}

function renderAdminSubmissions(){const p=$("admin-submissions-panel"),items=getStored("uu_submissions",[]);p.innerHTML=items.map(x=>`<article class="admin-item"><img src="${x.image}" alt="${escapeHtml(x.title)}"><div><div class="admin-item-top"><span class="status-pill ${x.status}">${x.status==="approved"?t("adminApproved"):t("adminPending")}</span><small>${new Date(x.createdAt).toLocaleString()}</small></div><h4>${escapeHtml(x.title)}</h4><p class="admin-author">${escapeHtml(x.name||"匿名投稿")}</p>${x.note?`<p>${escapeHtml(x.note)}</p>`:""}<div class="admin-actions">${x.status!=="approved"?`<button data-action="approve" data-id="${x.id}">${t("adminApprove")}</button>`:""}<button class="danger-button" data-action="delete" data-id="${x.id}">${t("adminDelete")}</button></div></div></article>`).join("")||`<p class="admin-empty">${t("adminEmpty")}</p>`;}
function renderAdminMessages(){const p=$("admin-messages-panel"),items=getStored("uu_private_messages",[]),blocked=getStored("uu_blocked_users",[]);p.innerHTML=`<div class="admin-private-tools"><strong>${t("blockedUsers")}</strong><div class="blocked-list">${blocked.map(n=>`<span class="blocked-chip">${escapeHtml(n)} <button type="button" data-unblock-user="${escapeHtml(n)}">×</button></span>`).join("")||`<span class="small-note">${t("noBlockedUsers")}</span>`}</div></div>`+(items.map(x=>{const isBlocked=blocked.includes(x.name||"匿名");return `<article class="private-admin-note ${isBlocked?"is-blocked":""}"><div class="admin-item-top"><span class="status-pill private">${t("adminPrivate")}</span><small>${new Date(x.createdAt).toLocaleString()}</small></div><h4>${escapeHtml(x.name||"匿名")}${isBlocked?` <span class="blocked-label">${t("blocked")}</span>`:""}</h4><p>${escapeHtml(x.message)}</p>${x.reply?`<div class="admin-reply-preview"><strong>${t("yourReply")}</strong><p>${escapeHtml(x.reply)}</p></div>`:""}<div class="private-actions"><button type="button" data-message-reply="${x.id}">${t("replyToMessage")}</button><button type="button" data-block-user="${escapeHtml(x.name||"匿名")}">${isBlocked?t("unblockUser"):t("blockUser")}</button><button type="button" class="danger-button" data-message-delete="${x.id}">${t("adminDelete")}</button></div><form class="private-reply-form hidden" data-reply-message-form="${x.id}"><textarea maxlength="500" placeholder="${t("replyMessagePlaceholder")}">${escapeHtml(x.reply||"")}</textarea><button type="submit" class="admin-save-main">${t("sendAdminReply")}</button></form></article>`}).join("")||`<p class="admin-empty">${t("adminNoMessages")}</p>`);}
function renderAdminTalks(){const p=$("admin-talk-panel");if(!p)return;const talks=getUuTalks();let box=p;box.innerHTML=`<h3>${t("editUuTalk")}</h3><label>${t("talkTitle")}</label><input id="talk-title" maxlength="80" placeholder="${t("talkTitlePlaceholder")}"><label>${t("talkText")}</label><textarea id="talk-text" maxlength="1000" placeholder="${t("talkTextPlaceholder")}"></textarea><label>${t("talkDate")}</label><input id="talk-date" type="date" value="${new Date().toISOString().slice(0,10)}"><button id="add-uu-talk" class="admin-save-main">${t("publishTalk")}</button><div class="admin-talk-list">${talks.map(x=>`<article><div><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.date||"")}</small><p>${escapeHtml(x.text)}</p></div><button class="danger-button" data-talk-delete="${x.id}">${t("adminDelete")}</button></article>`).join("")}</div>`;$("add-uu-talk").onclick=()=>{const title=$("talk-title").value.trim(),text=$("talk-text").value.trim();if(!title||!text)return;const a=getUuTalks();a.unshift({id:uid(),title,text,date:$("talk-date").value,createdAt:new Date().toISOString()});saveStored("uu_uu_talks",a);renderAdminTalks();renderUuTalks();};box.onclick=e=>{const b=e.target.closest("[data-talk-delete]");if(!b)return;saveStored("uu_uu_talks",getUuTalks().filter(x=>x.id!==b.dataset.talkDelete));renderAdminTalks();renderUuTalks();};}

$("admin-submissions-panel").addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;let a=getStored("uu_submissions",[]);if(b.dataset.action==="approve")a=a.map(x=>x.id===b.dataset.id?{...x,status:"approved"}:x);if(b.dataset.action==="delete")a=a.filter(x=>x.id!==b.dataset.id);saveStored("uu_submissions",a);renderAdminSubmissions();renderCommunityGallery();});
$("admin-messages-panel").addEventListener("click",e=>{const del=e.target.closest("[data-message-delete]");if(del){saveStored("uu_private_messages",getStored("uu_private_messages",[]).filter(x=>x.id!==del.dataset.messageDelete));renderAdminMessages();return;}const rep=e.target.closest("[data-message-reply]");if(rep){document.querySelector(`[data-reply-message-form="${rep.dataset.messageReply}"]`)?.classList.toggle("hidden");return;}const block=e.target.closest("[data-block-user]");if(block){const name=block.dataset.blockUser,blocked=getStored("uu_blocked_users",[]);saveStored("uu_blocked_users",blocked.includes(name)?blocked.filter(x=>x!==name):[...blocked,name]);renderAdminMessages();return;}const unblock=e.target.closest("[data-unblock-user]");if(unblock){saveStored("uu_blocked_users",getStored("uu_blocked_users",[]).filter(x=>x!==unblock.dataset.unblockUser));renderAdminMessages();}});
$("admin-messages-panel").addEventListener("submit",e=>{if(!e.target.matches("[data-reply-message-form]"))return;e.preventDefault();const id=e.target.dataset.replyMessageForm,text=e.target.querySelector("textarea").value.trim();if(!text)return;const a=getStored("uu_private_messages",[]);const item=a.find(x=>x.id===id);if(item){item.reply=text;item.repliedAt=new Date().toISOString();saveStored("uu_private_messages",a);renderAdminMessages();}});

function unlockAdmin(){if($("admin-password").value===ADMIN_PASSWORD){adminUnlocked=true;sessionStorage.setItem("uu_admin_unlocked","1");$("admin-locked").classList.add("hidden");$("admin-panel").classList.remove("hidden");$("admin-password").value="";renderAdminAll();}else $("admin-message").textContent=t("adminWrongPassword");}
$("admin-unlock").addEventListener("click",unlockAdmin);$("admin-password").addEventListener("keydown",e=>{if(e.key==="Enter")unlockAdmin();});
$("admin-lock").addEventListener("click",()=>{adminUnlocked=false;sessionStorage.removeItem("uu_admin_unlocked");$("admin-panel").classList.add("hidden");$("admin-locked").classList.remove("hidden");});
document.querySelectorAll(".admin-tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));tab.classList.add("active");const target=tab.dataset.adminTab;["editor","myart","submissions","messages","talk"].forEach(x=>$(`admin-${x}-panel`).classList.toggle("hidden",x!==target));}));
$("admin-open-upload")?.addEventListener("click",()=>{const tab=document.querySelector("[data-admin-tab=\"myart\"]");tab?.click();$("my-art-image")?.focus();});

$("language-toggle").addEventListener("click",()=>{language=language==="zh"?"en":"zh";applyLanguage();});

renderGuestbook();renderUuTalks();if(sessionStorage.getItem("uu_admin_unlocked")==="1"){adminUnlocked=true;$("admin-locked").classList.add("hidden");$("admin-panel").classList.remove("hidden");}
applyLanguage();
